### ISSUE TITLE
[Feature Reuqest] Extend the feature for scale the Sheet UI

### ISSUE THREAD

**Issue by p4535992** [cs96and/FoundryVTT-uiscaler#1]
I don't know if it is possible, or inherent to the module, but I would like to have a similar functionality to have "bigger" and scaled sheets.

**Comment by cs96and** [comment]
c292856c006cf5024b02a73e0c2da592004563f2

**Comment by cs96and** [comment]
v1.2.0 has support for scaling all app windows.
