### ISSUE TITLE
Hole UI moving up when a chat messages apears.

### ISSUE THREAD

**Issue by Kurokasa** [cs96and/FoundryVTT-uiscaler#2]
Hi, first of all thx for the awesome moduel :D

Foundry Version: 11.305
UI-Scaler Version: 1.2
Other Modules: all disabled.

With the first 2 Chat messages entering the chat, the hole UI is pushed up. Deleting the Chat and reloading fixes it, but the next chat will push it up again, reload with the chat filled doesnt fix it. I tried this in Chrome and Edge. There are no error etc. in the console.
Hope you can fix it, since i dont want to look at the giant normal UI :D, if you need more infos just ask :)

<img width="1310" alt="image" src="https://github.com/cs96and/FoundryVTT-uiscaler/assets/102412559/97f5894c-47da-4889-adf1-237d2bd01b49">
<img width="1312" alt="image" src="https://github.com/cs96and/FoundryVTT-uiscaler/assets/102412559/7b85a0ae-4e71-4a04-8ca2-582c505e9ba0">

**Comment by cs96and** [comment]
I noticed some weirdness with v11 too, but unfortunately I won't be able to take a look at this for a few weeks.

**Comment by Kronos25** [comment]
Adding my comment to reinforce that I'm having this issue as well.

**Comment by Kurokasa** [comment]
Hi, 
i played arround a bit and i might have found a fix. I send you a pull request, check it out when you have the time.
@Kronos25 its an easy fix in the uiscaler.css, if you dont want to wait maybe look in the pull request and try it out yourself.

**Comment by cs96and** [comment]
6782b69964aa8c5bc2389117e57a3c340a3146c1

**Comment by cs96and** [comment]
Fixed in 1.2.1

EDIT: no it's not. 1.2.2 incoming...

**Comment by cs96and** [comment]
This is now properly fixed in 1.2.2 (Thanks @Kurokasa for the PR).

I noticed that if you set the scale to 100% and then changed it later on, than the UI didn't move up, so I initially "fixed" it by setting the scale in the `ready` hook, instead of `setup`.  That initially looked like it worked, but typing into the chat box made it move up again.

I just went with @Kurokasa's version in the end.
